name: Deploy Vite App to Vercel

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Ensure you're using the version compatible with Vite

      - name: Install Dependencies
        run: cd form-validation && npm install

      - name: Build Project
        run: cd form-validation && npm run build

      - name: Deploy to Vercel
        run: cd form-validation && npx vercel --token=${{ secrets.VERCEL_TOKEN }} --prod --confirm
