name: Deploy Vite App to Vercel

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Ensure you're using the version compatible with Vite

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Check VERCEL_TOKEN
        run: |
          if [ -z "${{ secrets.VERCEL_TOKEN }}" ]; then
            echo "VERCEL_TOKEN is not set."
            exit 1
          fi
      - name: Deploy to Vercel
        run: npx vercel --token=${{ secrets.VERCEL_TOKEN }} --prod --confirm
